from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class ParameterSpec:
    key: str
    label: str
    minimum: int
    maximum: int
    default: int


CREATIVE_PARAMETER_SPECS = (
    ParameterSpec("creative_mix", "Dither Mix", 0, 100, 100),
    ParameterSpec("creative_orientation", "Quarter Turns", 0, 3, 0),
    ParameterSpec("creative_offset_x", "Pattern Offset X", -64, 64, 0),
    ParameterSpec("creative_offset_y", "Pattern Offset Y", -64, 64, 0),
    ParameterSpec("creative_jitter", "Threshold Jitter", 0, 100, 0),
    ParameterSpec("creative_seed", "Variation Seed", 0, 999, 0),
)


_KEY_SPECS = {
    "dither_parameter_slider": ("Amount", 1, 20, 1),
    "matrix_size_slider": ("Matrix Size", 1, 20, 4),
    "smoothing_factor_slider": ("Smoothing", 0, 100, 0),
    "bleed_fraction_slider": ("Bleed", 0, 100, 0),
    "line_emphasis_slider": ("Line Emphasis", 1, 10, 5),
    "modulation_strength_slider": ("Modulation Strength", 1, 10, 5),
    "horizontal_bias_slider": ("Horizontal Bias", 1, 10, 5),
    "contour_thresh_slider": ("Contour Threshold", 0, 100, 50),
    "line_mode_slider": ("Line Mode", 1, 3, 1),
    "smoothing_slider": ("Smoothing", 0, 5, 0),
    "line_space_slider": ("Line Spacing", 1, 5, 1),
    "wave_frequency_slider": ("Wave Frequency", 1, 20, 5),
    "wave_threshold_slider": ("Wave Threshold", 1, 30, 10),
    "diffusion_strength_slider": ("Diffusion Strength", 0, 200, 100),
    "lateral_spread_slider": ("Lateral Spread", 0, 200, 100),
    "downward_spread_slider": ("Downward Spread", 0, 200, 100),
    "direction_bias_slider": ("Direction Bias", 0, 100, 50),
    "error_response_slider": ("Error Response", 25, 200, 100),
    "noise_tail_slider": ("Noise Tail", 25, 200, 50),
    "horizontal_grain_slider": ("Horizontal Grain", 0, 100, 50),
    "vertical_grain_slider": ("Vertical Grain", 0, 100, 50),
    "noise_seed_slider": ("Noise Seed", 0, 999, 0),
    "threshold_contrast_slider": ("Threshold Contrast", 0, 200, 100),
    "threshold_bias_slider": ("Threshold Bias", -128, 128, 0),
    "matrix_rotation_slider": ("Matrix Rotation", 0, 3, 0),
    "matrix_offset_x_slider": ("Matrix Offset X", -32, 32, 0),
    "matrix_offset_y_slider": ("Matrix Offset Y", -32, 32, 0),
    "random_seed_slider": ("Random Seed", 0, 999, 0),
    "grain_width_slider": ("Grain Width", 1, 16, 1),
    "grain_height_slider": ("Grain Height", 1, 16, 1),
    "tile_threshold_scale_slider": ("Tile Threshold Scale", 0, 200, 100),
    "pattern_contrast_slider": ("Pattern Contrast", 0, 200, 100),
    "pattern_bias_slider": ("Pattern Bias", -128, 128, 0),
    "pattern_skew_slider": ("Pattern Skew", -4, 4, 0),
    "pattern_phase_y_slider": ("Pattern Phase Y", -32, 32, 0),
    "ray_count_slider": ("Ray Count", 2, 96, 24),
    "ray_phase_slider": ("Ray Phase", 0, 360, 0),
    "center_x_slider": ("Center X", -64, 64, 0),
    "center_y_slider": ("Center Y", -64, 64, 0),
    "threshold_span_slider": ("Threshold Span", 1, 128, 128),
    "wave_x_frequency_slider": ("X Frequency", 1, 100, 15),
    "wave_y_frequency_slider": ("Y Frequency", 1, 100, 15),
    "special_wave_phase_slider": ("Wave Phase", 0, 360, 0),
    "wave_x_weight_slider": ("X Weight", 0, 100, 50),
    "wave_amplitude_slider": ("Wave Amplitude", 1, 128, 128),
    "noise_amplitude_slider": ("Noise Amount", 0, 510, 255),
    "noise_bias_slider": ("Noise Bias", -255, 255, 0),
    "noise_grain_slider": ("Noise Grain", 1, 16, 1),
    "noise_image_mix_slider": ("Image Gain", 0, 200, 100),
    "topo_band_count_slider": ("Band Count", 2, 32, 8),
    "topo_warp_frequency_slider": ("Warp Frequency", 1, 100, 10),
    "topo_sample_step_slider": ("Contour Reach", 1, 8, 1),
    "topo_phase_slider": ("Warp Phase", 0, 360, 0),
    "threshold_x_scale_slider": ("X Frequency", 1, 10, 1),
    "threshold_y_scale_slider": ("Y Frequency", 1, 10, 1),
    "threshold_amplitude_slider": ("Modulation Depth", 0, 128, 64),
    "threshold_phase_slider": ("Phase", 0, 360, 0),
    "edge_x_weight_slider": ("X Edge Weight", 0, 200, 100),
    "edge_y_weight_slider": ("Y Edge Weight", 0, 200, 100),
    "edge_radius_slider": ("Edge Radius", 1, 8, 1),
    "edge_bias_slider": ("Edge Bias", -128, 128, 0),
    "contour_displacement_slider": ("Contour Displacement", 0, 32, 0),
    "sine_y_frequency_slider": ("Y Frequency", 0, 100, 10),
    "sine_phase_slider": ("Sine Phase", 0, 360, 0),
    "sine_contrast_slider": ("Darkness Gain", 0, 200, 100),
    "vortex_arms_slider": ("Spiral Arms", 1, 32, 6),
    "vortex_radial_frequency_slider": ("Radial Frequency", 1, 100, 15),
    "vortex_phase_slider": ("Vortex Phase", 0, 360, 0),
    "ring_frequency_slider": ("Ring Frequency", 1, 100, 30),
    "ring_phase_slider": ("Ring Phase", 0, 360, 0),
    "ring_ellipticity_slider": ("Ellipticity", 10, 300, 100),
    "wire_x_weight_slider": ("X Edge Weight", 0, 200, 100),
    "wire_y_weight_slider": ("Y Edge Weight", 0, 200, 100),
    "wire_diagonal_weight_slider": ("Diagonal Weight", 0, 200, 100),
    "wire_radius_slider": ("Edge Radius", 1, 8, 1),
    "hatch_vertical_gate_slider": ("Vertical Gate", 0, 100, 15),
    "hatch_horizontal_gate_slider": ("Horizontal Gate", 0, 100, 40),
    "hatch_diagonal_gate_slider": ("Diagonal Gate", 0, 100, 65),
    "hatch_steep_gate_slider": ("Counter-Diagonal Gate", 0, 100, 85),
    "artifact_base_frequency_slider": ("Base Frequency", 1, 50, 5),
    "artifact_tone_frequency_slider": ("Tone Frequency", 0, 50, 10),
    "artifact_amplitude_slider": ("Threshold Amplitude", 1, 128, 128),
    "artifact_phase_slider": ("Artifact Phase", 0, 360, 0),
    "vhs_line_width_slider": ("Tracking Width", 1, 12, 1),
    "vhs_line_brightness_slider": ("Tracking Brightness", 0, 255, 255),
    "vhs_spacing_curve_slider": ("Line Distribution", 25, 400, 100),
    "vhs_line_offset_slider": ("Line Offset", -64, 64, 0),
    "glitch_seed_slider": ("Glitch Seed", 0, 999, 0),
    "glitch_row_hold_slider": ("Band Height", 1, 32, 1),
    "glitch_direction_bias_slider": ("Direction Bias", 0, 100, 50),
    "glitch_wrap_slider": ("Wrap Rows", 0, 1, 1),
    "diffusion_error_gain_slider": ("Error Gain", 0, 200, 100),
    "diffusion_decay_slider": ("Carry Persistence", 0, 100, 0),
    "diffusion_row_phase_slider": ("Alternating Bias", -128, 128, 0),
    "diffusion_error_clamp_slider": ("Error Clamp", 0, 64, 0),
    "waveform_base_frequency_slider": ("Base Frequency", 1, 50, 5),
    "waveform_y_phase_slider": ("Row Phase", 0, 100, 30),
    "waveform_amplitude_slider": ("Threshold Amplitude", 1, 128, 128),
    "waveform_phase_slider": ("Waveform Phase", 0, 360, 0),
    "ordered_wobble_frequency_slider": ("Wobble Frequency", 1, 100, 20),
    "ordered_wobble_amplitude_slider": ("Wobble Depth", 0, 128, 40),
    "ordered_axis_weight_slider": ("Axis Balance", 0, 100, 50),
    "ordered_phase_slider": ("Ordered Phase", 0, 360, 0),
    "smooth_memory_slider": ("Carry Memory", 0, 200, 100),
    "stucki_near_weight_slider": ("Near Carry", 0, 100, 50),
    "stucki_far_weight_slider": ("Far Carry", 0, 100, 20),
    "stucki_vertical_weight_slider": ("Vertical Carry", 0, 100, 30),
    "stucki_final_threshold_slider": ("Output Threshold", 0, 255, 128),
    "atkinson_divisor_slider": ("Error Divisor", 1, 32, 8),
    "atkinson_far_weight_slider": ("Far Carry", 0, 200, 100),
    "atkinson_vertical_weight_slider": ("Vertical Carry", 0, 200, 100),
    "contrast_gain_slider": ("Contrast Gain", 0, 100, 25),
    "contrast_center_slider": ("Contrast Center", 0, 255, 64),
    "contrast_radius_slider": ("Contrast Radius", 1, 8, 1),
    "history_decay_slider": ("History Decay", 10, 75, 50),
    "path_error_gain_slider": ("Error Gain", 0, 200, 100),
    "local_threshold_slider": ("Local Threshold", -64, 64, 0),
    "curve_direction_slider": ("Curve Direction", 0, 1, 0),
    "path_center_x_slider": ("Path Center X", -32, 32, 0),
    "path_center_y_slider": ("Path Center Y", -32, 32, 0),
    "flow_alignment_slider": ("Flow Alignment", 0, 100, 100),
    "hatch_width_slider": ("Hatch Width", 25, 200, 100),
    "edge_flow_slider": ("Edge Flow", 25, 200, 100),
    "pattern_phase_slider": ("Pattern Phase", 0, 100, 0),
    "row_stagger_slider": ("Row Stagger", 0, 100, 50),
    "hex_shape_slider": ("Hex Shape", 0, 100, 35),
    "diagonal_slope_slider": ("Diagonal Slope", 25, 200, 100),
    "triangle_split_slider": ("Triangle Split", 0, 8, 2),
    "spiral_center_x_slider": ("Center X", -64, 64, 0),
    "spiral_center_y_slider": ("Center Y", -64, 64, 0),
    "spiral_twist_slider": ("Spiral Twist", -200, 200, 100),
    "engrave_width_slider": ("Engrave Width", 25, 200, 100),
    "reaction_feed_slider": ("Feed Rate", 50, 150, 100),
    "reaction_kill_slider": ("Kill Rate", 50, 150, 100),
    "chemical_diffusion_slider": ("Chemical Diffusion", 25, 175, 100),
    "reaction_seed_density_slider": ("Seed Density", 1, 30, 9),
    "wave_frequency_slider": ("Wave Frequency", 5, 100, 32),
    "angular_step_slider": ("Angular Step", 100, 400, 240),
    "wave_phase_slider": ("Wave Phase", 0, 200, 100),
    "interference_contrast_slider": ("Interference Contrast", 25, 200, 100),
    "bayer_cell_size_slider": ("Bayer Cell Size", 1, 16, 1),
    "wave_line_spacing_slider": ("Line Spacing", 25, 400, 100),
    "diffusion_line_spacing_slider": ("Line Spacing", 1, 20, 1),
    "echo_count_slider": ("Echo Count", 0, 16, 6),
    "echo_spacing_slider": ("Echo Spacing", 2, 40, 10),
    "echo_wave_amount_slider": ("Wave Amount", 0, 32, 8),
    "echo_wave_phase_slider": ("Wave Phase", 0, 360, 0),
    "echo_streak_slider": ("Streak Amount", 0, 100, 20),
    "echo_dissolve_slider": ("Dissolve Amount", 0, 100, 30),
    "echo_breath_slider": ("Breath", 0, 100, 50),
    "echo_wave_frequency_slider": ("Wave Frequency", 1, 100, 10),
    "fs_length_slider": ("Trail Length", 4, 64, 32),
    "fs_drift_slider": ("Drift", 1, 8, 2),
    "fs_noise_amount_slider": ("Noise Amount", 0, 24, 6),
    "fs_noise_scale_slider": ("Noise Scale", 1, 100, 20),
    "fs_decay_slider": ("Decay", 50, 100, 88),
    "fs_time_slider": ("Time", 0, 360, 0),
    "fs_erode_slider": ("Erode", 0, 100, 30),
    "fs_density_slider": ("Density", 0, 200, 100),
    "fs_lines_slider": ("Lines", 0, 100, 60),
    "fs_line_spacing_slider": ("Line Spacing", 8, 160, 48),
}

_STYLE_PARAMETERS = {
    ("Uniform Modulation Y", "smoothing_factor_slider"): ("Smoothing", 0, 100, 50),
    ("Uniform Modulation Y", "bleed_fraction_slider"): ("Bleed", 0, 100, 25),
    ("Uniform Modulation Y", "diffusion_decay_slider"): ("Carry Persistence", 0, 100, 10),
    ("Uniform Modulation X", "smoothing_factor_slider"): ("Smoothing", 0, 100, 0),
    ("Uniform Modulation X", "bleed_fraction_slider"): ("Bleed", 0, 100, 0),
    ("Uniform Modulation X", "diffusion_decay_slider"): ("Carry Persistence", 0, 100, 0),
    ("Topography Alt", "topo_band_count_slider"): ("Band Count", 2, 32, 12),
    ("Topography Alt", "topo_sample_step_slider"): ("Contour Reach", 1, 8, 2),
    ("Displace Contour", "contour_thresh_slider"): ("Tone Limit", 0, 100, 50),
    ("Displace Contour", "line_mode_slider"): ("Line Thickness", 1, 3, 1),
    ("Displace Contour", "smoothing_slider"): ("Contour Reach", 0, 5, 0),
    ("Displace Contour", "line_space_slider"): ("Contour Density", 1, 5, 1),
    ("Displace Contour", "contour_displacement_slider"): ("Contour Displacement", 0, 32, 0),
    ("Smooth Diffuse", "smoothness_slider"): ("Smoothness", 1, 10, 5),
    ("Checkers - Small", "pattern_scale_slider"): ("Checker Size", 1, 32, 2),
    ("Checkers - Medium", "pattern_scale_slider"): ("Checker Size", 1, 32, 4),
    ("Checkers - Large", "pattern_scale_slider"): ("Checker Size", 1, 32, 8),
    ("Diamond", "pattern_scale_slider"): ("Diamond Size", 2, 32, 8),
    ("Gridlock/Traffic", "pattern_scale_slider"): ("Grid Spacing", 2, 32, 6),
    ("Print Pattern", "pattern_scale_slider"): ("Print Cell Size", 2, 32, 6),
    ("Block Tone", "pattern_scale_slider"): ("Block Size", 2, 32, 4),
    ("Stippling", "pattern_scale_slider"): ("Stipple Sparsity", 1, 20, 1),
    ("Crosshatch", "pattern_scale_slider"): ("Line Spacing", 2, 32, 4),
    ("Dot Screen", "pattern_scale_slider"): ("Dot Cell Size", 2, 32, 6),
    ("Line Screen", "pattern_scale_slider"): ("Line Spacing", 2, 32, 6),
    ("Bayer-Void", "dither_parameter_slider"): ("Void Strength", 1, 20, 10),
    ("Mosaic", "dither_parameter_slider"): ("Tile Size", 1, 20, 10),
    ("Modulated Bayer Dither", "matrix_size_slider"): ("Matrix Size", 2, 3, 2),
    ("Halftone-Ordered", "dither_parameter_slider"): ("Dot Cell Size", 2, 20, 6),
    ("Bayer-Ordered", "matrix_rotation_slider"): ("Matrix Rotation", 0, 3, 0),
    ("Bit Tone", "dither_parameter_slider"): ("Tone Size", 1, 20, 1),
    ("Halftone-Ordered", "dither_parameter_slider"): ("Dot Size", 1, 20, 6),
    ("Spiral Path", "curve_direction_slider"): ("Curve Direction", 0, 1, 1),
    ("Hex Bayer", "threshold_contrast_slider"): ("Threshold Contrast", 25, 200, 100),
    ("Triangular", "threshold_contrast_slider"): ("Threshold Contrast", 25, 200, 100),
    ("Bayer-Matrix 4x4", "threshold_contrast_slider"): ("Threshold Contrast", 25, 200, 100),
    ("Bayer-Matrix 4x4", "matrix_offset_x_slider"): ("Matrix Offset X", -16, 16, 0),
    ("Bayer-Matrix 4x4", "matrix_offset_y_slider"): ("Matrix Offset Y", -16, 16, 0),
    ("Sine Wave Modulation", "wave_frequency_slider"): ("Wave Frequency", 1, 20, 5),
}

# The legacy registry deliberately reused ``dither_parameter_slider`` for many
# unrelated concepts.  Keep that stable preset key while presenting the user
# with the actual artistic control and the kernel's real default/range.
_STYLE_PRIMARY = {
    "Gaussian": ("Spread", 1, 20, 1),
    "Hilbert (Riemersma)": ("History Length", 1, 24, 8),
    "Spiral Path": ("Error Retention", 20, 95, 70),
    "Flow Hatch": ("Hatch Spacing", 2, 24, 6),
    "Hex Bayer": ("Cell Size", 1, 16, 3),
    "Triangular": ("Cell Size", 1, 16, 3),
    "Spiral Engrave": ("Spiral Pitch", 2, 24, 6),
    "Reaction-Diffusion": ("Iterations", 1, 20, 20),
    "Quasicrystal": ("Wave Count", 3, 7, 5),
    "Artifact Modulation": ("Artifact Amount", 1, 20, 1),
    "Atkinson-VHS": ("Line Count", 1, 20, 1),
    "Glitch": ("Glitch Intensity", 1, 20, 1),
    "Modulated Diffuse Y": ("Error Divisor", 1, 20, 1),
    "Modulated Diffuse X": ("Error Divisor", 1, 20, 1),
    "Uniform Modulation Y": ("Error Divisor", 1, 20, 2),
    "Uniform Modulation X": ("Error Divisor", 1, 20, 1),
    "Waveform": ("Wave Density", 1, 20, 1),
    "Waveform Alt": ("Modulation Blend", 1, 20, 1),
    "Ordered Modulation": ("Modulation Amount", 1, 20, 1),
    "Smooth Diffuse": ("Error Divisor", 1, 20, 1),
    "Contrast Aware Y": ("Error Divisor", 1, 20, 1),
    "Contrast Aware X": ("Error Divisor", 1, 20, 1),
    "Bayer-Void": ("Void Strength", 1, 20, 1),
    "Bit Tone": ("Tone Size", 1, 20, 1),
    "Mosaic": ("Tile Size", 1, 20, 1),
    "Halftone-Ordered": ("Dot Size", 1, 20, 1),
    "Block Tone": ("Block Size", 1, 20, 1),
    "Stippling": ("Stipple Density", 1, 20, 1),
    "Crosshatch": ("Line Spacing", 1, 20, 1),
    "Dot Screen": ("Dot Size", 1, 20, 1),
    "Line Screen": ("Line Spacing", 1, 20, 1),
    "Topography": ("Warp Intensity", 1, 20, 1),
    "Topography Alt": ("Warp Intensity", 1, 20, 3),
    "Thresholder": ("Line Spacing", 1, 20, 1),
    "Diagonal": ("Edge Sensitivity", 1, 20, 1),
    "Wireframe Alt": ("Edge Sensitivity", 1, 20, 1),
    "Crosshatch Alt": ("Line Spacing", 1, 20, 4),
}


def parameter_specs(entry) -> tuple[ParameterSpec, ...]:
    if entry.name == "None":
        return ()
    specs = list(CREATIVE_PARAMETER_SPECS)
    for key in entry.param_sliders:
        raw = _KEY_SPECS.get(key)
        if key == "dither_parameter_slider":
            raw = _STYLE_PRIMARY.get(entry.name, raw)
        # Exact style/key metadata wins over both the shared key and the legacy
        # primary-key presentation. Several old kernels reuse the same slider ID
        # with different historical defaults.
        raw = _STYLE_PARAMETERS.get((entry.name, key), raw)
        if raw is None:
            raise KeyError(f"Missing parameter metadata for {entry.name!r}: {key!r}")
        specs.append(ParameterSpec(key, *raw))
    return tuple(specs)
